# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-2
  template:
    metadata:
      labels:
        app: postgres-2
    spec:
      containers:
      - name: postgres-2
        image: postgres:latest  # Use the appropriate version
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: template1
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-2-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-2-secret
              key: password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-2-pvc
---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-2-service
spec:
  type: ClusterIP
  clusterIP: 10.43.94.125
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-2
---
# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-2-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cmVkaGF0

