# postgres-1-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-1-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/postgres-1
---
# postgres-1-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# postgres-1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-1
  template:
    metadata:
      labels:
        app: postgres-1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      containers:
      - name: postgres
        image: postgres:16.0
        command:
        - postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "redhat"
        - name: POSTGRES_DB
          value: "template1"
        - name: PGDATA
          value: "/data"
        volumeMounts:
        - name: pgdata
          mountPath: /data
        - name: config
          mountPath: /root/postgres-1/config
        - name: archive
          mountPath: /mnt/server/archive
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: postgres-1-pvc
      - name: config
        hostPath:
          path: /root/postgres-1/config
      - name: archive
        hostPath:
          path: /root/postgres-1/archive
---
# postgres-1-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-1-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-1

