# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-1
  template:
    metadata:
      labels:
        app: postgres-1
    spec:
      containers:
      - name: postgres-1
        image: postgres:latest  # Use the appropriate version
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: template1
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-1-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-1-secret
              key: password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-1-pvc
---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-1-service
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-1
---
# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-1-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cmVkaGF0
